In [ ]:
import numpy as np

In [ ]:
# 1. Array Assignment
arr = np.array([1,2,3])
print (arr)

[1 2 3]


In [ ]:
# 2. Range assignment
arr2 = np.arange(10)
print (arr2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 3. Single dim array
arr = np.array([1,2,3])

In [ ]:
#4. Two dim array
arr = np.array([[1,2,3],[4,5,6]])
print (arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#5. Three dim array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#6 Array size
arr.size

9

In [ ]:
#7 Array shape
arr.shape

(3, 3)

In [ ]:
#8 Array dim
arr.ndim

2

In [ ]:
#9 Array type
arr.dtype.name

'int64'

In [ ]:
#10 array type declaration. Complex number array
arr2 = np.array([1,2], dtype=complex)
print(arr2)

[1.+0.j 2.+0.j]


In [ ]:
#11 arraty type declaration.  Floating point number array
arr2 = np.array([1,2], dtype=float)
print(arr2)

[1. 2.]


In [ ]:
#12 Zero filled
arr2 = np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#13 Ones filled array with datatype
arr2 = np.ones( (2,3), dtype=np.int16)
print(arr2)

[[1 1 1]
 [1 1 1]]


In [ ]:
#14 empty array init
arr2 = np.empty( (2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#15 range
np.arange(1, 10,1)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#16 print
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#17 Reshape
arr2 = np.arange(0,10,1)
print(arr2)
print(arr2.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#18 multiply
arr2 = np.array([1,2,3])
arr3 = arr2*2
print(arr3)

[2 4 6]


In [ ]:
#19 trignometry
arr3 = np.sin(arr2)
print(arr3)

[0.84147098 0.90929743 0.14112001]


In [ ]:
#20 trignometry
arr3 = np.cos(arr2)
print(arr3)

[ 0.54030231 -0.41614684 -0.9899925 ]


In [ ]:
#21 trignometry
arr3 = np.tan(arr2)
print(arr3)

[ 1.55740772 -2.18503986 -0.14254654]


In [ ]:
#22 arrap ops
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a*b)

[1 4 9]


In [ ]:
#23 arrap ops
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b)

[2 4 6]


In [ ]:
#24 sum of elements
print(a.sum())

6


In [ ]:
#25 MAx od elements
print(max(a))

3


In [ ]:
#26 Min od elements
print(min(a))

1


In [ ]:
#27 index
print(arr2[1])

2


In [ ]:
#28 index range
a = np.arange(1,10,1)
print(a[2:5])

[3 4 5]


In [ ]:
#29 splitting
a = np.arange(1,10,1)
print(np.hsplit(a,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
#30 splitting
a = np.arange(1,10,1)
print(np.hsplit(a,(2,3)))

[array([1, 2]), array([3]), array([4, 5, 6, 7, 8, 9])]


In [ ]:
#31 copy
b=a
print(b)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#32 copy status
b=a
print(b is a)

True
